steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest tests/api_pytest_parameterized_test.py
        pytest tests/dag_api_unittest_test.py
        pytest tests/response_test.py
        
        # Send email with test results using smtplib
        python send_email.py
    timeout: '1200s'
images: ['python:3.8']

  


