steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest tests/api_pytest_parameterized_test.py
        python -m unittest tests/dag_api_unittest_test.py

timeout: '1200s'  # Set a reasonable timeout for your tests