steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt
        pytest api_pytest_parameterized.py dag_api_unittest.py

timeout: '1200s'  # Set a reasonable timeout for your tests