steps:
  - name: 'python'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install -r requirements.txt 

        for ((test_case_num=1; test_case_num<=30; test_case_num++)); do
          export TEST_CASE_NUM=$test_case_num

          pytest tests/api_pytest_parameterized_test.py
          pytest tests/dag_api_unittest_test.py
          pytest tests/response_test.py

          # Check if pytest exit code is 0 (success)
          if [ $? -eq 0 ]; then
            python send_email.py  # Running email script
          else
            echo "Tests failed for test case $test_case_num. Email not sent" 
          fi
        done
    timeout: '1200s'










  


